name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Run Backend Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "server"
          target: "/home/ubuntu/cpen321-project"

      - name: Rebuild and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/cpen321-project/server

            # Write secrets into .env
            printf "DB_URI=%s\nPORT=%s\nGCP_PROJECT_ID=%s\nGCP_CLIENT_EMAIL=%s\n" \
              "${{ secrets.PROD_DB_URI }}" \
              "${{ secrets.PROD_PORT }}" \
              "${{ secrets.PROJECTID }}" \
              "${{ secrets.CLIENTEMAIL }}" > .env

            # Write GCP_PRIVATE_KEY with quotes and newlines
            printf "GCP_PRIVATE_KEY=\"%s\"\n" "${{ secrets.PRIVATEKEY }}" >> .env

            # Give .env permissions
            chmod 600 .env

            # Build and run container
            docker-compose down
            docker-compose --env-file .env build
            docker-compose --env-file .env up -d
          
