name: Run Backend Tests

on:
  push:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Run tests
        env:
          DB_URI: ${{ secrets.PROD_DB_URI }}
          PORT: ${{ secrets.PROD_PORT }}
          GCP_PROJECT_ID: ${{ secrets.PROJECTID }}
          GCP_CLIENT_EMAIL: ${{ secrets.CLIENTEMAIL }}
          GCP_PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
        run: |
          cd server
          npm test --coverage

      - name: Create coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: server/coverage/
